version: "3"
services:
    frontend:
        container_name: client
        build:
            context: ./
            dockerfile: Dockerfile
        image: react
        ports:
            - "3123:3123"
        volumes:
            - ./client:/app
    backend:
        container_name: backend
        build:
            context: ../nestjs/todo-backend
            dockerfile: Dockerfile
        image: server
        ports:
            - "5123:5123"
        volumes:
            - ./server:/app
